Added types definition for TypeScript
sindresorhus/cli-cursor pull request #4
Opened 2018-08-03 18:42 UTC by DrunkenPoney

2018-09-12 09:25 UTC, sindresorhus commented
Thanks for creating a TypeScript definition. Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

2019-01-16 22:43 UTC, MrTarantula commented on package.json
> +    "types/index.d.ts"
To follow the guide, move this and other files from `types` folder to the root.

2019-01-16 22:44 UTC, MrTarantula commented on package.json
> +    "typescript": "^3.0.1",
TS is not necessary for development. Remove this dependency and `tsconfig.json`.

2019-01-16 22:48 UTC, MrTarantula commented on types/index.d.ts
> +declare function show(stream?: WritableStream): void;
This file needs [TSDoc comments](https://github.com/sindresorhus/typescript-definition-style-guide#documentation).

2019-02-01 05:06 UTC, sindresorhus commented
@DrunkenPoney Ping :)

2019-02-09 06:54 UTC, DrunkenPoney commented
Done! Sorry for the delay

2019-02-18 07:36 UTC, sindresorhus requested changes

2019-02-18 07:36 UTC, sindresorhus commented on index.d.ts
> + * @param stream (Default: process.stderr)
There should be a `-` here. See the style guide. Also see the style guide regarding `Default` formatting.

2019-02-18 07:36 UTC, sindresorhus commented on index.d.ts
> +declare function show(stream?: WritableStream): void;
Import `WritableStream` explicitly instead of using the implicit global.

2019-02-18 07:36 UTC, sindresorhus commented on index.d.ts
> + * @param force Useful to show or hide the cursor based on a boolean
Description should end in a `.`

2019-02-18 07:36 UTC, sindresorhus commented on test.ts
> +declare const process: {stdout: WritableStream};
This should be correctly imported and not declared.

2019-02-18 07:36 UTC, sindresorhus commented on index.d.ts
> +export {show, hide, toggle};
The export should be a default export.

2019-02-18 07:36 UTC, sindresorhus commented on test.ts
> +import {show, hide, toggle} from '..';
```suggestion
import cliCursor from '..';
```

2019-02-18 07:37 UTC, sindresorhus commented
> For packages with a default export, use export default foo;, not export = foo;. You will have to add module.exports.default = foo; to the index.js file.

> The pull request should have the title Add TypeScript definition. (Copy-paste it so you don't get it wrong)

2019-03-02 18:45 UTC, sindresorhus commented
Ping

2019-04-09 04:55 UTC, sindresorhus commented
Closing in favor of #5.

2019-04-09 04:55 UTC, closed without merging